name: "deploy-docs"
on:
  push:
    branches:
      - master
jobs:
  deploy-docs:
    runs-on: ubuntu-18.04
    container:
      image: python:3.7.8-buster
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: deploy-docs
        run: ./.github/workflows/deploy-docs.sh
